/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as TradeAnalyticsRouteImport } from './routes/trade-analytics'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as SharingCardsRouteImport } from './routes/sharing-cards'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PresentsRouteImport } from './routes/presents'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HuntsRouteImport } from './routes/hunts'
import { Route as HuntRouteImport } from './routes/hunt'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GoldFlairRouteImport } from './routes/gold-flair'
import { Route as GodpacksRouteImport } from './routes/godpacks'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CollectionMissionsRouteImport } from './routes/collection-missions'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CardRequestRouteImport } from './routes/card-request'
import { Route as BotHubRouteImport } from './routes/bot-hub'
import { Route as BattlesRouteImport } from './routes/battles'
import { Route as BattleStatsRouteImport } from './routes/battle-stats'
import { Route as BattleHistoryRouteImport } from './routes/battle-history'
import { Route as ApexTerminalRouteImport } from './routes/apex-terminal'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CollectionGoldFlairTradeRouteImport } from './routes/collection.gold-flair-trade'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeAnalyticsRoute = TradeAnalyticsRouteImport.update({
  id: '/trade-analytics',
  path: '/trade-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SharingCardsRoute = SharingCardsRouteImport.update({
  id: '/sharing-cards',
  path: '/sharing-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentsRoute = PresentsRouteImport.update({
  id: '/presents',
  path: '/presents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntsRoute = HuntsRouteImport.update({
  id: '/hunts',
  path: '/hunts',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntRoute = HuntRouteImport.update({
  id: '/hunt',
  path: '/hunt',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldFlairRoute = GoldFlairRouteImport.update({
  id: '/gold-flair',
  path: '/gold-flair',
  getParentRoute: () => rootRouteImport,
} as any)
const GodpacksRoute = GodpacksRouteImport.update({
  id: '/godpacks',
  path: '/godpacks',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionMissionsRoute = CollectionMissionsRouteImport.update({
  id: '/collection-missions',
  path: '/collection-missions',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRequestRoute = CardRequestRouteImport.update({
  id: '/card-request',
  path: '/card-request',
  getParentRoute: () => rootRouteImport,
} as any)
const BotHubRoute = BotHubRouteImport.update({
  id: '/bot-hub',
  path: '/bot-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlesRoute = BattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleStatsRoute = BattleStatsRouteImport.update({
  id: '/battle-stats',
  path: '/battle-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleHistoryRoute = BattleHistoryRouteImport.update({
  id: '/battle-history',
  path: '/battle-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApexTerminalRoute = ApexTerminalRouteImport.update({
  id: '/apex-terminal',
  path: '/apex-terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CollectionGoldFlairTradeRoute =
  CollectionGoldFlairTradeRouteImport.update({
    id: '/collection/gold-flair-trade',
    path: '/collection/gold-flair-trade',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/apex-terminal': typeof ApexTerminalRoute
  '/battle-history': typeof BattleHistoryRoute
  '/battle-stats': typeof BattleStatsRoute
  '/battles': typeof BattlesRoute
  '/bot-hub': typeof BotHubRoute
  '/card-request': typeof CardRequestRoute
  '/cards': typeof CardsRoute
  '/collection-missions': typeof CollectionMissionsRoute
  '/events': typeof EventsRoute
  '/gifts': typeof GiftsRoute
  '/godpacks': typeof GodpacksRoute
  '/gold-flair': typeof GoldFlairRoute
  '/help': typeof HelpRoute
  '/hunt': typeof HuntRoute
  '/hunts': typeof HuntsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/presents': typeof PresentsRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/sharing-cards': typeof SharingCardsRoute
  '/tracker': typeof TrackerRoute
  '/trade-analytics': typeof TradeAnalyticsRoute
  '/trades': typeof TradesRoute
  '/wishlist': typeof WishlistRoute
  '/collection/gold-flair-trade': typeof CollectionGoldFlairTradeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/analytics': typeof AnalyticsRoute
  '/apex-terminal': typeof ApexTerminalRoute
  '/battle-history': typeof BattleHistoryRoute
  '/battle-stats': typeof BattleStatsRoute
  '/battles': typeof BattlesRoute
  '/bot-hub': typeof BotHubRoute
  '/card-request': typeof CardRequestRoute
  '/cards': typeof CardsRoute
  '/collection-missions': typeof CollectionMissionsRoute
  '/events': typeof EventsRoute
  '/gifts': typeof GiftsRoute
  '/godpacks': typeof GodpacksRoute
  '/gold-flair': typeof GoldFlairRoute
  '/help': typeof HelpRoute
  '/hunt': typeof HuntRoute
  '/hunts': typeof HuntsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/presents': typeof PresentsRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/sharing-cards': typeof SharingCardsRoute
  '/tracker': typeof TrackerRoute
  '/trade-analytics': typeof TradeAnalyticsRoute
  '/trades': typeof TradesRoute
  '/wishlist': typeof WishlistRoute
  '/collection/gold-flair-trade': typeof CollectionGoldFlairTradeRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/apex-terminal': typeof ApexTerminalRoute
  '/battle-history': typeof BattleHistoryRoute
  '/battle-stats': typeof BattleStatsRoute
  '/battles': typeof BattlesRoute
  '/bot-hub': typeof BotHubRoute
  '/card-request': typeof CardRequestRoute
  '/cards': typeof CardsRoute
  '/collection-missions': typeof CollectionMissionsRoute
  '/events': typeof EventsRoute
  '/gifts': typeof GiftsRoute
  '/godpacks': typeof GodpacksRoute
  '/gold-flair': typeof GoldFlairRoute
  '/help': typeof HelpRoute
  '/hunt': typeof HuntRoute
  '/hunts': typeof HuntsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/presents': typeof PresentsRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/sharing-cards': typeof SharingCardsRoute
  '/tracker': typeof TrackerRoute
  '/trade-analytics': typeof TradeAnalyticsRoute
  '/trades': typeof TradesRoute
  '/wishlist': typeof WishlistRoute
  '/collection/gold-flair-trade': typeof CollectionGoldFlairTradeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/admin'
    | '/analytics'
    | '/apex-terminal'
    | '/battle-history'
    | '/battle-stats'
    | '/battles'
    | '/bot-hub'
    | '/card-request'
    | '/cards'
    | '/collection-missions'
    | '/events'
    | '/gifts'
    | '/godpacks'
    | '/gold-flair'
    | '/help'
    | '/hunt'
    | '/hunts'
    | '/inventory'
    | '/login'
    | '/presents'
    | '/profile'
    | '/resources'
    | '/settings'
    | '/sharing-cards'
    | '/tracker'
    | '/trade-analytics'
    | '/trades'
    | '/wishlist'
    | '/collection/gold-flair-trade'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/apex-terminal'
    | '/battle-history'
    | '/battle-stats'
    | '/battles'
    | '/bot-hub'
    | '/card-request'
    | '/cards'
    | '/collection-missions'
    | '/events'
    | '/gifts'
    | '/godpacks'
    | '/gold-flair'
    | '/help'
    | '/hunt'
    | '/hunts'
    | '/inventory'
    | '/login'
    | '/presents'
    | '/profile'
    | '/resources'
    | '/settings'
    | '/sharing-cards'
    | '/tracker'
    | '/trade-analytics'
    | '/trades'
    | '/wishlist'
    | '/collection/gold-flair-trade'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/admin'
    | '/analytics'
    | '/apex-terminal'
    | '/battle-history'
    | '/battle-stats'
    | '/battles'
    | '/bot-hub'
    | '/card-request'
    | '/cards'
    | '/collection-missions'
    | '/events'
    | '/gifts'
    | '/godpacks'
    | '/gold-flair'
    | '/help'
    | '/hunt'
    | '/hunts'
    | '/inventory'
    | '/login'
    | '/presents'
    | '/profile'
    | '/resources'
    | '/settings'
    | '/sharing-cards'
    | '/tracker'
    | '/trade-analytics'
    | '/trades'
    | '/wishlist'
    | '/collection/gold-flair-trade'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  ApexTerminalRoute: typeof ApexTerminalRoute
  BattleHistoryRoute: typeof BattleHistoryRoute
  BattleStatsRoute: typeof BattleStatsRoute
  BattlesRoute: typeof BattlesRoute
  BotHubRoute: typeof BotHubRoute
  CardRequestRoute: typeof CardRequestRoute
  CardsRoute: typeof CardsRoute
  CollectionMissionsRoute: typeof CollectionMissionsRoute
  EventsRoute: typeof EventsRoute
  GiftsRoute: typeof GiftsRoute
  GodpacksRoute: typeof GodpacksRoute
  GoldFlairRoute: typeof GoldFlairRoute
  HelpRoute: typeof HelpRoute
  HuntRoute: typeof HuntRoute
  HuntsRoute: typeof HuntsRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  PresentsRoute: typeof PresentsRoute
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  SharingCardsRoute: typeof SharingCardsRoute
  TrackerRoute: typeof TrackerRoute
  TradeAnalyticsRoute: typeof TradeAnalyticsRoute
  TradesRoute: typeof TradesRoute
  WishlistRoute: typeof WishlistRoute
  CollectionGoldFlairTradeRoute: typeof CollectionGoldFlairTradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-analytics': {
      id: '/trade-analytics'
      path: '/trade-analytics'
      fullPath: '/trade-analytics'
      preLoaderRoute: typeof TradeAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharing-cards': {
      id: '/sharing-cards'
      path: '/sharing-cards'
      fullPath: '/sharing-cards'
      preLoaderRoute: typeof SharingCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presents': {
      id: '/presents'
      path: '/presents'
      fullPath: '/presents'
      preLoaderRoute: typeof PresentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts': {
      id: '/hunts'
      path: '/hunts'
      fullPath: '/hunts'
      preLoaderRoute: typeof HuntsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunt': {
      id: '/hunt'
      path: '/hunt'
      fullPath: '/hunt'
      preLoaderRoute: typeof HuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-flair': {
      id: '/gold-flair'
      path: '/gold-flair'
      fullPath: '/gold-flair'
      preLoaderRoute: typeof GoldFlairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godpacks': {
      id: '/godpacks'
      path: '/godpacks'
      fullPath: '/godpacks'
      preLoaderRoute: typeof GodpacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection-missions': {
      id: '/collection-missions'
      path: '/collection-missions'
      fullPath: '/collection-missions'
      preLoaderRoute: typeof CollectionMissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card-request': {
      id: '/card-request'
      path: '/card-request'
      fullPath: '/card-request'
      preLoaderRoute: typeof CardRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-hub': {
      id: '/bot-hub'
      path: '/bot-hub'
      fullPath: '/bot-hub'
      preLoaderRoute: typeof BotHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battles': {
      id: '/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof BattlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle-stats': {
      id: '/battle-stats'
      path: '/battle-stats'
      fullPath: '/battle-stats'
      preLoaderRoute: typeof BattleStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle-history': {
      id: '/battle-history'
      path: '/battle-history'
      fullPath: '/battle-history'
      preLoaderRoute: typeof BattleHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apex-terminal': {
      id: '/apex-terminal'
      path: '/apex-terminal'
      fullPath: '/apex-terminal'
      preLoaderRoute: typeof ApexTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/collection/gold-flair-trade': {
      id: '/collection/gold-flair-trade'
      path: '/collection/gold-flair-trade'
      fullPath: '/collection/gold-flair-trade'
      preLoaderRoute: typeof CollectionGoldFlairTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  ApexTerminalRoute: ApexTerminalRoute,
  BattleHistoryRoute: BattleHistoryRoute,
  BattleStatsRoute: BattleStatsRoute,
  BattlesRoute: BattlesRoute,
  BotHubRoute: BotHubRoute,
  CardRequestRoute: CardRequestRoute,
  CardsRoute: CardsRoute,
  CollectionMissionsRoute: CollectionMissionsRoute,
  EventsRoute: EventsRoute,
  GiftsRoute: GiftsRoute,
  GodpacksRoute: GodpacksRoute,
  GoldFlairRoute: GoldFlairRoute,
  HelpRoute: HelpRoute,
  HuntRoute: HuntRoute,
  HuntsRoute: HuntsRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  PresentsRoute: PresentsRoute,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  SharingCardsRoute: SharingCardsRoute,
  TrackerRoute: TrackerRoute,
  TradeAnalyticsRoute: TradeAnalyticsRoute,
  TradesRoute: TradesRoute,
  WishlistRoute: WishlistRoute,
  CollectionGoldFlairTradeRoute: CollectionGoldFlairTradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
